version: '3'
services:
  gameserver:
    image: refresh:latest
    container_name: refresh-gameserver
    build: .
    restart: unless-stopped
    ports:
      - "10061:10061"
    environment:
      BUNKUM_DATA_FOLDER: /refresh/data
    healthcheck:
      # Fails if the /_health endpoint contains 'Unhealthy'
      test: ["CMD", "bash", "-c", "export UNHEALTHY=$(curl http://localhost:10061/_health --silent | grep -i Unhealthy); if [ '$UNHEALTHY' != '' ]; then exit 1; else exit 0; fi"]
      timeout: 3s
      interval: 5s
      retries: 5
    volumes:
      - "./data:/refresh/data:z"
